# Generated by Django 5.2.10 on 2026-01-09 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('mobility', '0002_alignement'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notemodule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='module',
            name='is_pfa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notemodule',
            name='campagne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mobility.campagne'),
        ),
        migrations.AlterUniqueTogether(
            name='notemodule',
            unique_together={('campagne', 'etudiant', 'module')},
        ),
    ]
