# Generated by Django 5.2.10 on 2026-01-10 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_module_is_tc'),
        ('mobility', '0002_alignement'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoyenneS3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moy_s3_avant_rattrapage', models.FloatField()),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moyennes_s3', to='mobility.campagne')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moyennes_s3', to='academic.etudiant')),
            ],
            options={
                'unique_together': {('etudiant', 'campagne')},
            },
        ),
    ]
