# Generated by Django 5.2.10 on 2026-01-09 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('mobility', '0002_alignement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametresSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seuil1', models.FloatField(default=12.5)),
                ('seuil2', models.FloatField(default=13.5)),
                ('min_pct', models.PositiveIntegerField(default=10)),
                ('max_pct', models.PositiveIntegerField(default=30)),
                ('campagne', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mobility.campagne')),
            ],
        ),
        migrations.CreateModel(
            name='AffectationFinale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mobilite', models.CharField(blank=True, choices=[('EC', 'Echange'), ('DD', 'Double Diplome')], max_length=2, null=True)),
                ('choix_obtenu', models.PositiveIntegerField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('AFFECTE', 'Affecte'), ('LISTE_ATTENTE', 'Liste attente'), ('NON_RETENU', 'Non retenu'), ('NON_PUBLIE', 'Non publie')], default='NON_PUBLIE', max_length=20)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobility.campagne')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.etudiant')),
                ('partenaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mobility.partenaire')),
            ],
            options={
                'unique_together': {('campagne', 'etudiant')},
            },
        ),
        migrations.CreateModel(
            name='ConvocationEntretien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entretien', models.DateTimeField(blank=True, null=True)),
                ('convoque', models.BooleanField(default=True)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobility.campagne')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.etudiant')),
            ],
            options={
                'unique_together': {('campagne', 'etudiant')},
            },
        ),
        migrations.CreateModel(
            name='DossierEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redoublement_a1', models.BooleanField(default=False)),
                ('blame', models.BooleanField(default=False)),
                ('moyenne_s3_avant_rattrapage', models.FloatField(blank=True, null=True)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobility.campagne')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.etudiant')),
            ],
            options={
                'unique_together': {('campagne', 'etudiant')},
            },
        ),
        migrations.CreateModel(
            name='ResultatEntretien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=True)),
                ('engagement_financier_ok', models.BooleanField(default=False)),
                ('motivation_ok', models.BooleanField(default=False)),
                ('decision', models.CharField(choices=[('RETENU', 'Retenu'), ('ELIMINE', 'Elimine'), ('EN_ATTENTE', 'En attente')], default='EN_ATTENTE', max_length=20)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobility.campagne')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.etudiant')),
            ],
            options={
                'unique_together': {('campagne', 'etudiant')},
            },
        ),
        migrations.CreateModel(
            name='ResultatPasse1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyenne_a1_sans_pfa', models.FloatField()),
                ('eligible', models.BooleanField(default=False)),
                ('motif_refus', models.CharField(blank=True, default='', max_length=255)),
                ('date_calcul', models.DateTimeField(auto_now=True)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobility.campagne')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.etudiant')),
            ],
            options={
                'unique_together': {('campagne', 'etudiant')},
            },
        ),
        migrations.CreateModel(
            name='ResultatPasse3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_selection', models.FloatField()),
                ('rang', models.PositiveIntegerField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('FIFO', 'FIFO'), ('ATTENTE', 'Liste attente'), ('NON_RETENU', 'Non retenu')], default='FIFO', max_length=20)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobility.campagne')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.etudiant')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.filiere')),
            ],
            options={
                'unique_together': {('campagne', 'etudiant')},
            },
        ),
    ]
