# Generated by Django 5.2.10 on 2026-01-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultatpasse3',
            name='note_s1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultatpasse3',
            name='note_s3',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
