# Generated by Django 5.2.10 on 2026-01-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0002_resultatpasse3_note_s1_resultatpasse3_note_s3'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='convocationentretien',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='convocationentretien',
            name='lieu',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='convocationentretien',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='convocationentretien',
            name='statut_convocation',
            field=models.CharField(default='CONVOQUE', max_length=50),
        ),
        migrations.RemoveField(
            model_name='convocationentretien',
            name='convoque',
        ),
    ]
