# Generated by Django 5.2.10 on 2026-01-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0003_alter_convocationentretien_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultatentretien',
            name='commentaire',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultatentretien',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='affectationfinale',
            name='statut',
            field=models.CharField(choices=[('AFFECTE', 'Affecte'), ('LISTE_ATTENTE', 'Liste attente'), ('NON_RETENU', 'Non retenu'), ('NON_PUBLIE', 'Non publie'), ('CONVOQUE', 'Convoqué Entretien'), ('ADMIS_DEFINITIF', 'Admis Définitif')], default='NON_PUBLIE', max_length=20),
        ),
        migrations.AlterField(
            model_name='resultatentretien',
            name='decision',
            field=models.CharField(choices=[('VALIDE', 'Validé'), ('REFUSE', 'Refusé'), ('EN_ATTENTE', 'En attente')], default='EN_ATTENTE', max_length=20),
        ),
    ]
