# Generated by Django 5.2.10 on 2026-01-14 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_moyennes3'),
        ('selection', '0004_resultatentretien_commentaire_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dossieretudiant',
            options={'ordering': ['classement', '-score_global']},
        ),
        migrations.RemoveField(
            model_name='parametresselection',
            name='campagne',
        ),
        migrations.RemoveField(
            model_name='parametresselection',
            name='seuil1',
        ),
        migrations.RemoveField(
            model_name='parametresselection',
            name='seuil2',
        ),
        migrations.RemoveField(
            model_name='resultatentretien',
            name='engagement_financier_ok',
        ),
        migrations.RemoveField(
            model_name='resultatentretien',
            name='motivation_ok',
        ),
        migrations.AddField(
            model_name='convocationentretien',
            name='commentaire',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='convocationentretien',
            name='est_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='convocationentretien',
            name='jury',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='convocationentretien',
            name='note_entretien',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dossieretudiant',
            name='classement',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dossieretudiant',
            name='decision_finale',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dossieretudiant',
            name='eligible',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dossieretudiant',
            name='motif',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dossieretudiant',
            name='moyenne_calculee_p1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dossieretudiant',
            name='score_academique_p2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dossieretudiant',
            name='score_global',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parametresselection',
            name='seuil_admissibilite_p2',
            field=models.FloatField(default=10.0, verbose_name='Seuil Score Global'),
        ),
        migrations.AddField(
            model_name='parametresselection',
            name='seuil_eligibilite_p1',
            field=models.FloatField(default=12.5, verbose_name='Seuil Moyenne 1A'),
        ),
        migrations.AddField(
            model_name='resultatpasse1',
            name='est_eligible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resultatpasse1',
            name='moyenne_generale',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultatpasse3',
            name='score_final',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='affectationfinale',
            name='statut',
            field=models.CharField(choices=[('AFFECTE', 'Affecté'), ('LISTE_ATTENTE', "Liste d'attente"), ('NON_RETENU', 'Non retenu'), ('NON_PUBLIE', 'Non publié'), ('DESISTEMENT', 'Désistement')], default='NON_PUBLIE', max_length=50),
        ),
        migrations.AlterField(
            model_name='parametresselection',
            name='max_pct',
            field=models.PositiveIntegerField(blank=True, default=30, null=True),
        ),
        migrations.AlterField(
            model_name='parametresselection',
            name='min_pct',
            field=models.PositiveIntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='resultatpasse1',
            name='moyenne_a1_sans_pfa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultatpasse3',
            name='filiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.filiere'),
        ),
        migrations.AlterField(
            model_name='resultatpasse3',
            name='note_selection',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
