# Generated by Django 5.2.10 on 2026-01-11 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('mobility', '0002_alignement'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='partenaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='mobility.partenaire'),
        ),
    ]
