# Generated by Django 5.2.10 on 2026-01-13 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_moyennes3'),
        ('accounts', '0003_alter_profile_partenaire_alter_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='partenaire',
        ),
        migrations.AddField(
            model_name='profile',
            name='filiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.filiere'),
        ),
    ]
