# Generated by Django 5.2.10 on 2026-01-15 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_partenaire_profile_filiere'),
        ('mobility', '0003_decisionpartenaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='partenaire',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_partenaire', to='mobility.partenaire'),
        ),
    ]
