# Generated by Django 5.2.10 on 2026-01-09 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_alter_notemodule_unique_together_module_is_pfa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='is_tc',
            field=models.BooleanField(default=False),
        ),
    ]
