# Generated by Django 5.2.10 on 2026-01-15 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_moyennes3'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='moyenne_1a_spec',
            field=models.FloatField(blank=True, help_text='Moyenne Spécialité', null=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='moyenne_1a_tc',
            field=models.FloatField(blank=True, help_text='Moyenne Tronc Commun', null=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='moyenne_generale',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='moyenne_s3',
            field=models.FloatField(blank=True, help_text='Moyenne S3 (Filtre)', null=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='score_selection',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='filiere',
            name='nombre_inscrits_2a',
            field=models.PositiveIntegerField(default=0, help_text="Nombre total d'étudiants inscrits en 2ème année (Base des Quotas)"),
        ),
        migrations.AlterField(
            model_name='moyennes3',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moyennes_s3_history', to='academic.etudiant'),
        ),
    ]
