# Generated by Django 5.2.10 on 2026-01-11 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_partenaire'),
        ('mobility', '0003_decisionpartenaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='partenaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mobility.partenaire'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('SCOLARITE', 'Scolarite'), ('SRI', 'SRI'), ('PARTENAIRE', 'Partenaire'), ('CF', 'Coordinateur Filiere'), ('COMITE', 'Comite Selection')], default='STUDENT', max_length=20),
        ),
    ]
