# Generated by Django 5.2.10 on 2026-01-09 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campagne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.CharField(max_length=9, unique=True)),
                ('date_ouverture_desiderata', models.DateTimeField()),
                ('date_cloture_desiderata', models.DateTimeField()),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_ecole', models.CharField(max_length=255, unique=True)),
                ('pays', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OffrePartenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filiere_accueil', models.CharField(max_length=255)),
                ('nb_places_ec', models.PositiveIntegerField(default=0)),
                ('nb_places_dd', models.PositiveIntegerField(default=0)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobility.campagne')),
                ('filiere_origine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.filiere')),
                ('partenaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobility.partenaire')),
            ],
            options={
                'unique_together': {('campagne', 'partenaire', 'filiere_origine', 'filiere_accueil')},
            },
        ),
        migrations.CreateModel(
            name='Desiderata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filiere_accueil', models.CharField(max_length=255)),
                ('type_mobilite', models.CharField(choices=[('EC', 'Echange'), ('DD', 'Double Diplome')], max_length=2)),
                ('priorite', models.PositiveIntegerField()),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé')], default='EN_ATTENTE', max_length=20)),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobility.campagne')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.etudiant')),
                ('partenaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobility.partenaire')),
            ],
            options={
                'ordering': ['priorite'],
                'unique_together': {('campagne', 'etudiant', 'priorite')},
            },
        ),
    ]
