# Generated by Django 5.2.10 on 2026-01-11 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_moyennes3'),
        ('mobility', '0002_alignement'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionPartenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('ACCEPTE', 'Accepté'), ('REFUSE', 'Refusé'), ('EN_ATTENTE', 'En attente')], default='EN_ATTENTE', max_length=20)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobility.campagne')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.etudiant')),
                ('partenaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobility.partenaire')),
            ],
            options={
                'unique_together': {('campagne', 'partenaire', 'etudiant')},
            },
        ),
    ]
