# Generated by Django 5.2.10 on 2026-01-09 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('mobility', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alignement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filiere_accueil', models.CharField(max_length=255)),
                ('type_mobilite', models.CharField(choices=[('EC', 'Echange'), ('DD', 'Double Diplome')], max_length=2)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobility.campagne')),
                ('filiere_origine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.filiere')),
                ('partenaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobility.partenaire')),
            ],
            options={
                'unique_together': {('campagne', 'filiere_origine', 'partenaire', 'filiere_accueil', 'type_mobilite')},
            },
        ),
    ]
