# Generated by Django 5.2.10 on 2026-01-15 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_moyennes3'),
        ('mobility', '0003_decisionpartenaire'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='offrepartenaire',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='offrepartenaire',
            name='filiere_accueil',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='offrepartenaire',
            name='filiere_origine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offres_partenaire', to='academic.filiere'),
        ),
        migrations.AlterField(
            model_name='offrepartenaire',
            name='nb_places_dd',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='offrepartenaire',
            name='nb_places_ec',
            field=models.IntegerField(default=0),
        ),
    ]
