# Generated by Django 5.2.10 on 2026-01-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_moyennes3'),
        ('mobility', '0004_alter_offrepartenaire_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offrepartenaire',
            options={'ordering': ['partenaire', 'filiere_accueil']},
        ),
        migrations.RemoveField(
            model_name='offrepartenaire',
            name='filiere_origine',
        ),
        migrations.AddField(
            model_name='offrepartenaire',
            name='filieres_ensias',
            field=models.ManyToManyField(blank=True, related_name='offres_partenaire', to='academic.filiere'),
        ),
        migrations.AlterField(
            model_name='offrepartenaire',
            name='filiere_accueil',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='offrepartenaire',
            name='nb_places_dd',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='offrepartenaire',
            name='nb_places_ec',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
